<?php

/**
 * Autogenerated base class for the Streams model.
 * 
 * Don't change this file, since it can be overwritten.
 * Instead, change the Streams.php file.
 *
 * @module Streams
 */
/**
 * Base class for the Streams model
 * @class Base_Streams
 */
abstract class Base_Streams
{
	/**
	 * The list of model classes
	 * @property $table_classnames
	 * @type array
	 */
	static $table_classnames = array (
  0 => 'Streams_Access',
  1 => 'Streams_Avatar',
  2 => 'Streams_Category',
  3 => 'Streams_Invite',
  4 => 'Streams_Invited',
  5 => 'Streams_Message',
  6 => 'Streams_MessageTotal',
  7 => 'Streams_Metrics',
  8 => 'Streams_Notification',
  9 => 'Streams_Participant',
  10 => 'Streams_RelatedFrom',
  11 => 'Streams_RelatedFromTotal',
  12 => 'Streams_RelatedTo',
  13 => 'Streams_RelatedToTotal',
  14 => 'Streams_Request',
  15 => 'Streams_State',
  16 => 'Streams_Stream',
  17 => 'Streams_Subscription',
  18 => 'Streams_SubscriptionRule',
  19 => 'Streams_Task',
);

	/**
     * This method calls Db.connect() using information stored in the configuration.
     * If this has already been called, then the same db object is returned.
	 * @method db
	 * @return {Db_Interface} The database object
	 */
	static function db()
	{
		return Db::connect('Streams');
	}

	/**
	 * The connection name for the class
	 * @method connectionName
	 * @return {string} The name of the connection
	 */
	static function connectionName()
	{
		return 'Streams';
	}
};