<?php

/**
 * Autogenerated base class for the Platform model.
 * 
 * Don't change this file, since it can be overwritten.
 * Instead, change the Platform.php file.
 *
 * @module Platform
 */
/**
 * Base class for the Platform model
 * @class Base_Platform
 */
abstract class Base_Platform
{
	/**
	 * The list of model classes
	 * @property $table_classnames
	 * @type array
	 */
	static $table_classnames = array (
  0 => 'Platform_Autocomplete',
  1 => 'Platform_Domain',
  2 => 'Platform_HostnameSession',
  3 => 'Platform_Publisher',
  4 => 'Platform_Session',
  5 => 'Platform_Share',
  6 => 'Platform_Visit',
  7 => 'Platform_Zipcode',
);

	/**
     * This method calls Db.connect() using information stored in the configuration.
     * If this has already been called, then the same db object is returned.
	 * @method db
	 * @return {iDb} The database object
	 */
	static function db()
	{
		return Db::connect('Platform');
	}

	/**
	 * The connection name for the class
	 * @method connectionName
	 * @return {string} The name of the connection
	 */
	static function connectionName()
	{
		return 'Platform';
	}
};